name: deploy

on:
  push:
    branches:
      - main

permissions:
  issues: read

env:
  GH_URL: https://api.github.com
  GH_REPO: analogical
  GH_OWNER: ricardocasares
  PUBLISHED_LABEL: published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: node-modules-
      - run: bun install
      - run: bun run build
      - name: upload build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
